export type WorldAreaType = "world" | "continent" | "country";

export interface WorldAreaData {
    key: string;
    name: string;
    type: WorldAreaType;
    subAreas?: string[];
}

export type WorldAreas = WorldAreaData[];

export type WorldAreasMap = { [key: string]: WorldAreaData };

export const worldAreas: WorldAreasMap = {
    world: { key: "world", name: "World", type: "world", subAreas: ["asia", "africa", "europe", "northAmerica", "southAmerica", "australiaOceania"] },
    
    // Continents
    asia: { key: "asia", name: "Asia", type: "continent", subAreas: ["afghanistan", "armenia", "azerbaijan", "bahrain", "bangladesh", "bhutan", "bruneiDarussalam", "cambodia", "china", "cyprus", "georgia", "hongKong", "india", "indonesia", "iran", "iraq", "israel", "japan", "jordan", "kazakhstan", "kuwait", "kyrgyzstan", "laos", "lebanon", "macao", "malaysia", "maldives", "mongolia", "myanmar", "nepal", "northKorea", "oman", "pakistan", "philippines", "qatar", "russia", "saudiArabia", "singapore", "southKorea", "sriLanka", "stateOfPalestine", "syria", "taiwan", "tajikistan", "thailand", "timorLeste", "turkey", "turkmenistan", "unitedArabEmirates", "uzbekistan", "vietnam", "yemen"] },
    africa: { key: "africa", name: "Africa", type: "continent", subAreas: ["algeria", "angola", "benin", "botswana", "burkinaFaso", "burundi", "caboVerde", "cameroon", "centralAfricanRepublic", "chad", "comoros", "congo", "côteD'ivoire", "democraticRepublicOfTheCongo", "djibouti", "egypt", "equatorialGuinea", "eritrea", "eswatini", "ethiopia", "gabon", "gambia", "ghana", "guinea", "guineaBissau", "kenya", "lesotho", "liberia", "libya", "madagascar", "malawi", "mali", "mauritania", "mauritius", "mayotte", "morocco", "mozambique", "namibia", "niger", "nigeria", "rwanda", "réunion", "saintHelena", "saoTomeAndPrincipe", "senegal", "seychelles", "sierraLeone", "somalia", "southAfrica", "southSudan", "sudan", "tanzania", "togo", "tunisia", "uganda", "westernSahara", "zambia", "zimbabwe"] },
    europe: { key: "europe", name: "Europe", type: "continent", subAreas: ["albania", "andorra", "austria", "belarus", "belgium", "bosniaAndHerzegovina", "bulgaria", "channelIslands", "croatia", "czechia", "denmark", "estonia", "faeroeIslands", "finland", "france", "germany", "gibraltar", "greece", "holySee", "hungary", "iceland", "ireland", "isleOfMan", "italy", "latvia", "liechtenstein", "lithuania", "luxembourg", "malta", "moldova", "monaco", "montenegro", "netherlands", "northMacedonia", "norway", "poland", "portugal", "romania", "russia", "sanMarino", "serbia", "slovakia", "slovenia", "spain", "sweden", "switzerland", "ukraine", "unitedKingdom"] },
    northAmerica: { key: "northAmerica", name: "North America", type: "continent", subAreas: ["anguilla", "antiguaAndBarbuda", "aruba", "bahamas", "barbados", "belize", "bermuda", "britishVirginIslands", "canada", "caribbeanNetherlands", "caymanIslands", "costaRica", "cuba", "curaçao", "dominica", "dominicanRepublic", "elSalvador", "greenland", "grenada", "guadeloupe", "guatemala", "haiti", "honduras", "jamaica", "martinique", "mexico", "montserrat", "nicaragua", "panama", "puertoRico", "saintBarthélemy", "saintKittsAndNevis", "saintLucia", "saintMartin", "saintPierreAndMiquelon", "saintVincentAndTheGrenadines", "sintMaarten", "trinidadAndTobago", "turksAndCaicosIslands", "usa", "unitedStatesVirginIslands"] },
    southAmerica: { key: "southAmerica", name: "South America", type: "continent", subAreas: ["argentina", "bolivia", "brazil", "chile", "colombia", "ecuador", "falklandIslands", "frenchGuiana", "guyana", "paraguay", "peru", "suriname", "uruguay", "venezuela"] },
    australiaOceania: { key: "australiaOceania", name: "Australia/Oceania", type: "continent", subAreas: ["americanSamoa", "australia", "cookIslands", "fiji", "frenchPolynesia", "guam", "kiribati", "marshallIslands", "micronesia", "nauru", "newCaledonia", "newZealand", "niue", "northernMarianaIslands", "palau", "papuaNewGuinea", "samoa", "solomonIslands", "tokelau", "tonga", "tuvalu", "vanuatu", "wallisAndFutunaIslands"] },
    
    // Asia
    afghanistan: { key: "afghanistan", name: "Afghanistan", type: "country" },
    armenia: { key: "armenia", name: "Armenia", type: "country" },
    azerbaijan: { key: "azerbaijan", name: "Azerbaijan", type: "country" },
    bahrain: { key: "bahrain", name: "Bahrain", type: "country" },
    bangladesh: { key: "bangladesh", name: "Bangladesh", type: "country" },
    bhutan: { key: "bhutan", name: "Bhutan", type: "country" },
    bruneiDarussalam: { key: "bruneiDarussalam", name: "Brunei Darussalam", type: "country" },
    cambodia: { key: "cambodia", name: "Cambodia", type: "country" },
    china: { key: "china", name: "China", type: "country" },
    cyprus: { key: "cyprus", name: "Cyprus", type: "country" },
    georgia: { key: "georgia", name: "Georgia", type: "country" },
    hongKong: { key: "hongKong", name: "Hong Kong", type: "country" },
    india: { key: "india", name: "India", type: "country" },
    indonesia: { key: "indonesia", name: "Indonesia", type: "country" },
    iran: { key: "iran", name: "Iran", type: "country" },
    iraq: { key: "iraq", name: "Iraq", type: "country" },
    israel: { key: "israel", name: "Israel", type: "country" },
    japan: { key: "japan", name: "Japan", type: "country" },
    jordan: { key: "jordan", name: "Jordan", type: "country" },
    kazakhstan: { key: "kazakhstan", name: "Kazakhstan", type: "country" },
    kuwait: { key: "kuwait", name: "Kuwait", type: "country" },
    kyrgyzstan: { key: "kyrgyzstan", name: "Kyrgyzstan", type: "country" },
    laos: { key: "laos", name: "Laos", type: "country" },
    lebanon: { key: "lebanon", name: "Lebanon", type: "country" },
    macao: { key: "macao", name: "Macao", type: "country" },
    malaysia: { key: "malaysia", name: "Malaysia", type: "country" },
    maldives: { key: "maldives", name: "Maldives", type: "country" },
    mongolia: { key: "mongolia", name: "Mongolia", type: "country" },
    myanmar: { key: "myanmar", name: "Myanmar", type: "country" },
    nepal: { key: "nepal", name: "Nepal", type: "country" },
    northKorea: { key: "northKorea", name: "North Korea", type: "country" },
    oman: { key: "oman", name: "Oman", type: "country" },
    pakistan: { key: "pakistan", name: "Pakistan", type: "country" },
    philippines: { key: "philippines", name: "Philippines", type: "country" },
    qatar: { key: "qatar", name: "Qatar", type: "country" },
    saudiArabia: { key: "saudiArabia", name: "Saudi Arabia", type: "country" },
    singapore: { key: "singapore", name: "Singapore", type: "country" },
    southKorea: { key: "southKorea", name: "South Korea", type: "country" },
    sriLanka: { key: "sriLanka", name: "Sri Lanka", type: "country" },
    stateOfPalestine: { key: "stateOfPalestine", name: "State of Palestine", type: "country" },
    syria: { key: "syria", name: "Syria", type: "country" },
    taiwan: { key: "taiwan", name: "Taiwan", type: "country" },
    tajikistan: { key: "tajikistan", name: "Tajikistan", type: "country" },
    thailand: { key: "thailand", name: "Thailand", type: "country" },
    timorLeste: { key: "timorLeste", name: "Timor-Leste", type: "country" },
    turkey: { key: "turkey", name: "Turkey", type: "country" },
    turkmenistan: { key: "turkmenistan", name: "Turkmenistan", type: "country" },
    unitedArabEmirates: { key: "unitedArabEmirates", name: "United Arab Emirates", type: "country" },
    uzbekistan: { key: "uzbekistan", name: "Uzbekistan", type: "country" },
    vietnam: { key: "vietnam", name: "Vietnam", type: "country" },
    yemen: { key: "yemen", name: "Yemen", type: "country" },
    
    // Africa
    algeria: { key: "algeria", name: "Algeria", type: "country" },
    angola: { key: "angola", name: "Angola", type: "country" },
    benin: { key: "benin", name: "Benin", type: "country" },
    botswana: { key: "botswana", name: "Botswana", type: "country" },
    burkinaFaso: { key: "burkinaFaso", name: "Burkina Faso", type: "country" },
    burundi: { key: "burundi", name: "Burundi", type: "country" },
    caboVerde: { key: "caboVerde", name: "Cabo Verde", type: "country" },
    cameroon: { key: "cameroon", name: "Cameroon", type: "country" },
    centralAfricanRepublic: { key: "centralAfricanRepublic", name: "Central African Republic", type: "country" },
    chad: { key: "chad", name: "Chad", type: "country" },
    comoros: { key: "comoros", name: "Comoros", type: "country" },
    congo: { key: "congo", name: "Congo", type: "country" },
    "côteD'ivoire": { key: "côteD'ivoire", name: "Côte d'Ivoire", type: "country" },
    democraticRepublicOfTheCongo: { key: "democraticRepublicOfTheCongo", name: "Democratic Republic of the Congo", type: "country" },
    djibouti: { key: "djibouti", name: "Djibouti", type: "country" },
    egypt: { key: "egypt", name: "Egypt", type: "country" },
    equatorialGuinea: { key: "equatorialGuinea", name: "Equatorial Guinea", type: "country" },
    eritrea: { key: "eritrea", name: "Eritrea", type: "country" },
    eswatini: { key: "eswatini", name: "Eswatini", type: "country" },
    ethiopia: { key: "ethiopia", name: "Ethiopia", type: "country" },
    gabon: { key: "gabon", name: "Gabon", type: "country" },
    gambia: { key: "gambia", name: "Gambia", type: "country" },
    ghana: { key: "ghana", name: "Ghana", type: "country" },
    guinea: { key: "guinea", name: "Guinea", type: "country" },
    guineaBissau: { key: "guineaBissau", name: "Guinea-Bissau", type: "country" },
    kenya: { key: "kenya", name: "Kenya", type: "country" },
    lesotho: { key: "lesotho", name: "Lesotho", type: "country" },
    liberia: { key: "liberia", name: "Liberia", type: "country" },
    libya: { key: "libya", name: "Libya", type: "country" },
    madagascar: { key: "madagascar", name: "Madagascar", type: "country" },
    malawi: { key: "malawi", name: "Malawi", type: "country" },
    mali: { key: "mali", name: "Mali", type: "country" },
    mauritania: { key: "mauritania", name: "Mauritania", type: "country" },
    mauritius: { key: "mauritius", name: "Mauritius", type: "country" },
    mayotte: { key: "mayotte", name: "Mayotte", type: "country" },
    morocco: { key: "morocco", name: "Morocco", type: "country" },
    mozambique: { key: "mozambique", name: "Mozambique", type: "country" },
    namibia: { key: "namibia", name: "Namibia", type: "country" },
    niger: { key: "niger", name: "Niger", type: "country" },
    nigeria: { key: "nigeria", name: "Nigeria", type: "country" },
    rwanda: { key: "rwanda", name: "Rwanda", type: "country" },
    réunion: { key: "réunion", name: "Réunion", type: "country" },
    saintHelena: { key: "saintHelena", name: "Saint Helena", type: "country" },
    saoTomeAndPrincipe: { key: "saoTomeAndPrincipe", name: "Sao Tome and Principe", type: "country" },
    senegal: { key: "senegal", name: "Senegal", type: "country" },
    seychelles: { key: "seychelles", name: "Seychelles", type: "country" },
    sierraLeone: { key: "sierraLeone", name: "Sierra Leone", type: "country" },
    somalia: { key: "somalia", name: "Somalia", type: "country" },
    southAfrica: { key: "southAfrica", name: "South Africa", type: "country" },
    southSudan: { key: "southSudan", name: "South Sudan", type: "country" },
    sudan: { key: "sudan", name: "Sudan", type: "country" },
    tanzania: { key: "tanzania", name: "Tanzania", type: "country" },
    togo: { key: "togo", name: "Togo", type: "country" },
    tunisia: { key: "tunisia", name: "Tunisia", type: "country" },
    uganda: { key: "uganda", name: "Uganda", type: "country" },
    westernSahara: { key: "westernSahara", name: "Western Sahara", type: "country" },
    zambia: { key: "zambia", name: "Zambia", type: "country" },
    zimbabwe: { key: "zimbabwe", name: "Zimbabwe", type: "country" },
    
    // Europe
    albania: { key: "albania", name: "Albania", type: "country" },
    andorra: { key: "andorra", name: "Andorra", type: "country" },
    austria: { key: "austria", name: "Austria", type: "country" },
    belarus: { key: "belarus", name: "Belarus", type: "country" },
    belgium: { key: "belgium", name: "Belgium", type: "country" },
    bosniaAndHerzegovina: { key: "bosniaAndHerzegovina", name: "Bosnia and Herzegovina", type: "country" },
    bulgaria: { key: "bulgaria", name: "Bulgaria", type: "country" },
    channelIslands: { key: "channelIslands", name: "Channel Islands", type: "country" },
    croatia: { key: "croatia", name: "Croatia", type: "country" },
    czechia: { key: "czechia", name: "Czechia", type: "country" },
    denmark: { key: "denmark", name: "Denmark", type: "country" },
    estonia: { key: "estonia", name: "Estonia", type: "country" },
    faeroeIslands: { key: "faeroeIslands", name: "Faeroe Islands", type: "country" },
    finland: { key: "finland", name: "Finland", type: "country" },
    france: { key: "france", name: "France", type: "country" },
    germany: { key: "germany", name: "Germany", type: "country" },
    gibraltar: { key: "gibraltar", name: "Gibraltar", type: "country" },
    greece: { key: "greece", name: "Greece", type: "country" },
    holySee: { key: "holySee", name: "Holy See", type: "country" },
    hungary: { key: "hungary", name: "Hungary", type: "country" },
    iceland: { key: "iceland", name: "Iceland", type: "country" },
    ireland: { key: "ireland", name: "Ireland", type: "country" },
    isleOfMan: { key: "isleOfMan", name: "Isle of Man", type: "country" },
    italy: { key: "italy", name: "Italy", type: "country" },
    latvia: { key: "latvia", name: "Latvia", type: "country" },
    liechtenstein: { key: "liechtenstein", name: "Liechtenstein", type: "country" },
    lithuania: { key: "lithuania", name: "Lithuania", type: "country" },
    luxembourg: { key: "luxembourg", name: "Luxembourg", type: "country" },
    malta: { key: "malta", name: "Malta", type: "country" },
    moldova: { key: "moldova", name: "Moldova", type: "country" },
    monaco: { key: "monaco", name: "Monaco", type: "country" },
    montenegro: { key: "montenegro", name: "Montenegro", type: "country" },
    netherlands: { key: "netherlands", name: "Netherlands", type: "country" },
    northMacedonia: { key: "northMacedonia", name: "North Macedonia", type: "country" },
    norway: { key: "norway", name: "Norway", type: "country" },
    poland: { key: "poland", name: "Poland", type: "country" },
    portugal: { key: "portugal", name: "Portugal", type: "country" },
    romania: { key: "romania", name: "Romania", type: "country" },
    russia: { key: "russia", name: "Russia", type: "country" }, // Also Asia
    sanMarino: { key: "sanMarino", name: "San Marino", type: "country" },
    serbia: { key: "serbia", name: "Serbia", type: "country" },
    slovakia: { key: "slovakia", name: "Slovakia", type: "country" },
    slovenia: { key: "slovenia", name: "Slovenia", type: "country" },
    spain: { key: "spain", name: "Spain", type: "country" },
    sweden: { key: "sweden", name: "Sweden", type: "country" },
    switzerland: { key: "switzerland", name: "Switzerland", type: "country" },
    ukraine: { key: "ukraine", name: "Ukraine", type: "country" },
    unitedKingdom: { key: "unitedKingdom", name: "United Kingdom", type: "country", },
    
    // North America
    anguilla: { key: "anguilla", name: "Anguilla", type: "country" },
    antiguaAndBarbuda: { key: "antiguaAndBarbuda", name: "Antigua and Barbuda", type: "country" },
    aruba: { key: "aruba", name: "Aruba", type: "country" },
    bahamas: { key: "bahamas", name: "Bahamas", type: "country" },
    barbados: { key: "barbados", name: "Barbados", type: "country" },
    belize: { key: "belize", name: "Belize", type: "country" },
    bermuda: { key: "bermuda", name: "Bermuda", type: "country" },
    britishVirginIslands: { key: "britishVirginIslands", name: "British Virgin Islands", type: "country" },
    canada: { key: "canada", name: "Canada", type: "country" },
    caribbeanNetherlands: { key: "caribbeanNetherlands", name: "Caribbean Netherlands", type: "country" },
    caymanIslands: { key: "caymanIslands", name: "Cayman Islands", type: "country" },
    costaRica: { key: "costaRica", name: "Costa Rica", type: "country" },
    cuba: { key: "cuba", name: "Cuba", type: "country" },
    curaçao: { key: "curaçao", name: "Curaçao", type: "country" },
    dominica: { key: "dominica", name: "Dominica", type: "country" },
    dominicanRepublic: { key: "dominicanRepublic", name: "Dominican Republic", type: "country" },
    elSalvador: { key: "elSalvador", name: "El Salvador", type: "country" },
    greenland: { key: "greenland", name: "Greenland", type: "country" },
    grenada: { key: "grenada", name: "Grenada", type: "country" },
    guadeloupe: { key: "guadeloupe", name: "Guadeloupe", type: "country" },
    guatemala: { key: "guatemala", name: "Guatemala", type: "country" },
    haiti: { key: "haiti", name: "Haiti", type: "country" },
    honduras: { key: "honduras", name: "Honduras", type: "country" },
    jamaica: { key: "jamaica", name: "Jamaica", type: "country" },
    martinique: { key: "martinique", name: "Martinique", type: "country" },
    mexico: { key: "mexico", name: "Mexico", type: "country" },
    montserrat: { key: "montserrat", name: "Montserrat", type: "country" },
    nicaragua: { key: "nicaragua", name: "Nicaragua", type: "country" },
    panama: { key: "panama", name: "Panama", type: "country" },
    puertoRico: { key: "puertoRico", name: "Puerto Rico", type: "country" },
    saintBarthélemy: { key: "saintBarthélemy", name: "Saint Barthélemy", type: "country" },
    saintKittsAndNevis: { key: "saintKittsAndNevis", name: "Saint Kitts and Nevis", type: "country" },
    saintLucia: { key: "saintLucia", name: "Saint Lucia", type: "country" },
    saintMartin: { key: "saintMartin", name: "Saint Martin", type: "country" },
    saintPierreAndMiquelon: { key: "saintPierreAndMiquelon", name: "Saint Pierre and Miquelon", type: "country" },
    saintVincentAndTheGrenadines: { key: "saintVincentAndTheGrenadines", name: "Saint Vincent and the Grenadines", type: "country" },
    sintMaarten: { key: "sintMaarten", name: "Sint Maarten", type: "country" },
    trinidadAndTobago: { key: "trinidadAndTobago", name: "Trinidad and Tobago", type: "country" },
    turksAndCaicosIslands: { key: "turksAndCaicosIslands", name: "Turks and Caicos Islands", type: "country" },
    usa: { key: "usa", name: "USA", type: "country" },
    unitedStatesVirginIslands: { key: "unitedStatesVirginIslands", name: "United States Virgin Islands", type: "country" },
    
    // South America
    argentina: { key: "argentina", name: "Argentina", type: "country" },
    bolivia: { key: "bolivia", name: "Bolivia", type: "country" },
    brazil: { key: "brazil", name: "Brazil", type: "country" },
    chile: { key: "chile", name: "Chile", type: "country" },
    colombia: { key: "colombia", name: "Colombia", type: "country" },
    ecuador: { key: "ecuador", name: "Ecuador", type: "country" },
    falklandIslands: { key: "falklandIslands", name: "Falkland Islands", type: "country" },
    frenchGuiana: { key: "frenchGuiana", name: "French Guiana", type: "country" },
    guyana: { key: "guyana", name: "Guyana", type: "country" },
    paraguay: { key: "paraguay", name: "Paraguay", type: "country" },
    peru: { key: "peru", name: "Peru", type: "country" },
    suriname: { key: "suriname", name: "Suriname", type: "country" },
    uruguay: { key: "uruguay", name: "Uruguay", type: "country" },
    venezuela: { key: "venezuela", name: "Venezuela", type: "country" },
    
    // Australia/Oceania
    americanSamoa: { key: "americanSamoa", name: "American Samoa", type: "country" },
    australia: { key: "australia", name: "Australia", type: "country" },
    cookIslands: { key: "cookIslands", name: "Cook Islands", type: "country" },
    fiji: { key: "fiji", name: "Fiji", type: "country" },
    frenchPolynesia: { key: "frenchPolynesia", name: "French Polynesia", type: "country" },
    guam: { key: "guam", name: "Guam", type: "country" },
    kiribati: { key: "kiribati", name: "Kiribati", type: "country" },
    marshallIslands: { key: "marshallIslands", name: "Marshall Islands", type: "country" },
    micronesia: { key: "micronesia", name: "Micronesia", type: "country" },
    nauru: { key: "nauru", name: "Nauru", type: "country" },
    newCaledonia: { key: "newCaledonia", name: "New Caledonia", type: "country" },
    newZealand: { key: "newZealand", name: "New Zealand", type: "country" },
    niue: { key: "niue", name: "Niue", type: "country" },
    northernMarianaIslands: { key: "northernMarianaIslands", name: "Northern Mariana Islands", type: "country" },
    palau: { key: "palau", name: "Palau", type: "country" },
    papuaNewGuinea: { key: "papuaNewGuinea", name: "Papua New Guinea", type: "country" },
    samoa: { key: "samoa", name: "Samoa", type: "country" },
    solomonIslands: { key: "solomonIslands", name: "Solomon Islands", type: "country" },
    tokelau: { key: "tokelau", name: "Tokelau", type: "country" },
    tonga: { key: "tonga", name: "Tonga", type: "country" },
    tuvalu: { key: "tuvalu", name: "Tuvalu", type: "country" },
    vanuatu: { key: "vanuatu", name: "Vanuatu", type: "country" },
    wallisAndFutunaIslands: { key: "wallisAndFutunaIslands", name: "Wallis and Futuna Islands", type: "country" },
};

function pickByType(type: WorldAreaType): WorldAreasMap {
    const obj: WorldAreasMap = {};
    for (const key in worldAreas) {
        if (worldAreas[key].type === type) {
            obj[key] = worldAreas[key];
        }
    }
    return obj;
}

export const world = pickByType("world");
export const continents = pickByType("continent");
export const countries = pickByType("country");

export const worldAreasArray: WorldAreas = [
    ...Object.values(world).sort((a, b) => a.key.localeCompare(b.key)),
    ...Object.values(continents).sort((a, b) => a.key.localeCompare(b.key)),
    ...Object.values(countries).sort((a, b) => a.key.localeCompare(b.key)),
];

export function getContinentsByCountry(country: string): string[] {
    const matchingContinents: string[] = [];
    for (const key in continents) {
        const continent = continents[key];
        if (continent.subAreas?.includes(country)) {
            matchingContinents.push(continent.key);
        }
    }
    return matchingContinents;
}
